# Generated by Django 3.1.7 on 2023-04-25 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20230423_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(default='images/default.png', help_text='Upload ảnh sản phẩm', upload_to='media/images/', verbose_name='Ảnh'),
        ),
    ]
