# Generated by Django 3.1.7 on 2023-05-04 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20230504_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(default='images/default.png', help_text='Upload ảnh sản phẩm', upload_to='images', verbose_name='Ảnh'),
        ),
    ]
